// Mapping of nationality (e.g., "Canadian") to country (e.g., "Canada")
export const nationalityToCountry = {
  Canadian: "Canada",
  Spanish: "Spain",
  British: "United Kingdom",
  French: "France",
  German: "Germany",
  Italian: "Italy",
  Dutch: "Netherlands",
  Australian: "Australia",
  Brazilian: "Brazil",
  American: "United States",
  Finnish: "Finland",
  Russian: "Russia",
  Belgian: "Belgium",
  Swiss: "Switzerland",
  Mexican: "Mexico",
  Japanese: "Japan",
  Austrian: "Austria",
  Swedish: "Sweden",
  Indian: "India",
  Chinese: "China",
  Hungarian: "Hungary",
  Polish: "Poland",
  Malaysian: "Malaysia",
  Danish: "Denmark",
  Portuguese: "Portugal",
  "South African": "South Africa",
  Thai: "Thailand",
  Turkish: "Turkey",
  Romanian: "Romania",
  Czech: "Czech Republic",
  Argentinian: "Argentina",
  Vietnamese: "Vietnam",
  Slovak: "Slovakia",
  Estonian: "Estonia",
  Croatian: "Croatia",
  Monegasque: "Monaco",
  "New Zealander": "New Zealand",
};

// Mapping of country name to ISO country code
export const countryToIsoCode = {
  Canada: "CA",
  Spain: "ES",
  "United Kingdom": "GB",
  France: "FR",
  Germany: "DE",
  Italy: "IT",
  Netherlands: "NL",
  Australia: "AU",
  Brazil: "BR",
  "United States": "US",
  Finland: "FI",
  Russia: "RU",
  Belgium: "BE",
  Switzerland: "CH",
  Mexico: "MX",
  Japan: "JP",
  Austria: "AT",
  Sweden: "SE",
  India: "IN",
  China: "CN",
  Hungary: "HU",
  Poland: "PL",
  Malaysia: "MY",
  Denmark: "DK",
  Portugal: "PT",
  "South Africa": "ZA",
  Thailand: "TH",
  Turkey: "TR",
  Romania: "RO",
  "Czech Republic": "CZ",
  Argentina: "AR",
  Vietnam: "VN",
  Slovakia: "SK",
  Estonia: "EE",
  Croatia: "HR",
  Monaco: "MC",
  "New Zealand": "NZ",
};
